---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Verify user input for required variables
      tags: project
      assert:
        that:
          - project_name is defined
          - project_path is defined


    - name: Ensure project directories
      tags: project
      with_items: "{{ project_dirs }}"
      file:
        state: directory
        path: "{{ project_path }}/{{ project_name }}/{{ item }}"

    - name: Install static files
      tags: project
      with_items:
        - "{{ project_files|selectattr('src', 'defined')|list }}"
        - "{{ project_files|selectattr('content', 'defined')|list }}"
      copy:
        src: "{{ item.src|default(omit) }}"
        dest: "{{ project_path }}/{{ project_name }}/{{ item.dest }}"
        mode: "{{ item.mode|default(0600) }}"
        force: "{{ item.force|default(false) }}"
        content: "{{ item.content|default(omit) }}"

    - name: Install templated files
      tags: project
      with_items:
        - "{{ project_files|selectattr('template', 'defined')|list }}"
      template:
        src: "templates/{{ item.template }}"
        dest: "{{ project_path }}/{{ project_name }}/{{ item.dest }}"
        mode: "{{ item.mode|default(0600) }}"
        force: "{{ item.force|default(false) }}"

    - name: Install empty files
      tags: project
      with_items: "{{ project_files|selectattr('empty', 'defined')|list }}"
      copy:
        dest: "{{ project_path }}/{{ project_name }}/{{ item.dest }}"
        content: ""
        mode: "{{ item.mode|default(0600) }}"
        force: "{{ item.force|default(false) }}"


    - name: Include tasks to manage git
      tags:
        - project
        - git
      when: project_manage_with_git
      include: tasks/git.yml
      vars:
        target: "{{ project_path }}/{{ project_name }}"


    - name: baem!
      tags: project
      debug:
        msg: "Find the Ansible project at {{ project_path }}/{{ project_name }}"
