---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    - project_name: ""
    - project_path: ""
  tasks:
    - name: Verify user input for required variables
      tags: project
      assert:
        that:
          - project_name != ""
          - project_path != ""

    - name: Set project_name_nodash
      set_fact:
        project_name_nodash: "{{ project_name|replace('-', '') }}"

    - name: Create Directories
      tags: project
      with_items: "{{ project_dirs }}"
      file:
        state: directory
        path: "{{ project_path }}/{{ project_name }}/{{ item.dest }}"

    - name: Copy templated Files
      tags: project
      with_items:
        - "{{ project_files|selectattr('src', 'defined')|list }}"
        - "{{ project_files|selectattr('content', 'defined')|list }}"
      copy:
        dest: "{{ project_path }}/{{ project_name }}/{{ item.dest }}"
        src: "{{ item.src|default(omit) }}"
        content: "{{ item.content|default(omit) }}"
        force: "{{ item.force|default(false) }}"

    - name: Create Templated Files
      tags: project
      with_items:
        - "{{ project_files|selectattr('template', 'defined')|list }}"
      template:
        src: "templates/{{ item.template }}"
        dest: "{{ project_path }}/{{ project_name }}/{{ item.dest }}"
        force: "{{ item.force|default(false) }}"

    - name: Create empty Files
      tags: project
      with_items: "{{ project_files|selectattr('empty', 'defined')|list }}"
      copy:
        dest: "{{ project_path }}/{{ project_name }}/{{ item.dest }}"
        content: ""
        force: "{{ item.force|default(false) }}"

    - name: echo {{ project_path }}/{{ project_name }}
      tags: project
      debug:
        msg: "Find the Ansible project at {{ project_path }}/{{ project_name }}"
