---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    - role_name: ""
    - role_path: ""
    - role_prefix: 'ansible'
    - update: false
    - git: true
  tasks:
    - name: Verify user input for required variables
      tags: role
      assert:
        that:
          - role_name !=  ""
          - role_path !=  ""
          - role_prefix in ['ansible', 'galaxy', 'silpion', 'infra']

    - name: Set role_name_nodash
      tags: role
      set_fact:
        role_name_nodash: "{{ role_name | replace('-','') }}"

    - name: Install Ansible role
      tags: role
      command: "ansible-galaxy init --init-path {{ role_path }} {{ role_prefix }}-{{ role_name }}"
      args:
        creates: "{{ role_path }}/{{ role_prefix}}-{{ role_name }}"

    - name: Install .gitignore
      tags: role
      copy:
        mode: 0600
        force: false
        src: files/role/.gitignore
        dest: "{{ role_path }}/{{ role_prefix}}-{{ role_name }}/.gitignore"

    - name: Install static files
      tags: role
      with_items:
        - CHANGELOG.md
        - LICENSE
        - VERSION
      copy:
        mode: 0600
        force: false
        src: "files/role/{{ item }}"
        dest: "{{ role_path }}/{{ role_prefix }}-{{ role_name }}/{{ item }}"

    - name: Install directories
      tags: role
      with_items:
        - rake
        - scripts
        - spec/default
        - spec/lib
        - tests
      file:
        state: directory
        dest: "{{ role_path }}/{{ role_prefix}}-{{ role_name }}/{{ item }}"

    - name: Install static files for TDD
      tags: role
      with_items:
        - ansible.cfg
        - Gemfile
        - rake/docker.rb
        - Rakefile
        - spec/lib/docker.rb
        - spec/lib/vagrant.rb
        - spec/spec_helper.rb
        - tests/hosts
        - tests/silpion-insecure-private-key
        - .travis.yml
      copy:
        mode: 0600
        src: "files/role/{{ item }}"
        dest: "{{ role_path }}/{{ role_prefix}}-{{ role_name }}/{{ item }}"

    - name: Install templates
      tags: role
      with_items:
        - README.md
        - tests/playbook.yml
        - vars/main.yml
      when: not update
      template:
        mode: 0600
        src: "templates/role/{{ item }}.j2"
        dest: "{{ role_path }}/{{ role_prefix}}-{{ role_name }}/{{ item }}"

    - name: Install templates for TDD
      tags: role
      with_items:
        - tests/docker.yml
        - Vagrantfile
        - envvars-vagrant.sample
        - rake/vagrant.rb
      template:
        mode: 0600
        src: "templates/role/{{ item }}.j2"
        dest: "{{ role_path }}/{{ role_prefix}}-{{ role_name }}/{{ item }}"

    - name: Install spec integration test file
      tags: role
      copy:
        mode: 0600
        force: false
        src: files/role/spec/default/rolename_spec.rb
        dest: "{{ role_path }}/{{ role_prefix}}-{{ role_name }}/spec/default/{{ role_name }}_spec.rb"

    - name: Install scripts
      tags: role
      with_items:
        - scripts/release.sh
      copy:
        mode: 0755
        src: "files/role/{{ item }}"
        dest: "{{ role_path }}/{{ role_prefix}}-{{ role_name }}/{{ item }}"

    - name: git init...
      tags: role
      when: git
      register: generater_git_init
      command: git init
      args:
        chdir: "{{ role_path }}/{{ role_prefix}}-{{ role_name }}"
        creates: "{{ role_path }}/{{ role_prefix}}-{{ role_name }}/.git"

    - name: git add...
      tags: role
      register: generator_git_add
      when: generater_git_init.changed
      command: git add .
      args:
        chdir: "{{ role_path }}/{{ role_prefix}}-{{ role_name }}"

    - name: git commit...
      tags: role
      when: generator_git_add.changed
      command: git commit -m 'Root commit (ansible-generator)'
      args:
        chdir: "{{ role_path }}/{{ role_prefix}}-{{ role_name }}"

    - name: echo {{ role_path }}/{{ role_prefix }}-{{ role_name }}
      tags: role
      debug:
        msg: "Find the Ansible role at {{ role_path }}/{{ role_prefix }}-{{ role_name }}"
