---
- name: Install Ansible role boilerplate
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Verify user input for required variables
      tags: always
      assert:
        that:
          - role_name is defined
          - role_path is defined
          - role_prefix|default('ansible') in role_allowed_role_prefixes


    - name: Install Ansible role boilerplate
      tags: role
      command: "ansible-galaxy init --init-path {{ role_path }} {{ role_name_final }}"
      args:
        creates: "{{ role_dest }}"


    - name: Ensure role directories
      tags: role
      with_items: "{{ role_dirs }}"
      file:
        state: directory
        dest: "{{ role_dest }}/{{ item }}"

    - name: Install static files
      tags: role
      with_items:
        - "{{ role_files|selectattr('src', 'defined')|list }}"
        - "{{ role_files|selectattr('content', 'defined')|list }}"
      copy:
        src: "{{ item.src|default(omit) }}"
        dest: "{{ role_dest }}/{{ item.dest|mandatory }}"
        mode: "{{ item.mode|default(0600) }}"
        force: "{{ item.force|default(false) }}"
        content: "{{ item.content|default(omit) }}"

    - name: Install templated files
      tags: role
      with_items: "{{ role_files|selectattr('template', 'defined')|list }}"
      template:
        src: "templates/{{ item.template }}"
        dest: "{{ role_dest }}/{{ item.dest|mandatory }}"
        mode: "{{ item.mode|default(0600) }}"
        force: "{{ item.force|default(false) }}"


    - name: Ensure state absent
      tags: role
      with_items: "{{ role_files_absent }}"
      file:
        state: absent
        dest: "{{ item }}"


    - name: Include tasks to manage git
      tags:
        - role
        - git
      when: role_manage_with_git
      include: tasks/git.yml
      vars:
        target: "{{ role_dest }}"


    - name: baem!
      tags: role
      debug:
        msg: "Find the Ansible role at {{ role_dest }}"
