---
# whether to git init a freshly created project
project_manage_with_git: true

# install these directories in a project
project_dirs:
  - files
  - group_vars
  - group_vars/all
  - group_vars/prod
  - group_vars/test
  - group_vars/stage
  - group_vars/vagrant
  - host_vars
  - templates
  - vars

# project_files configures files to install
#   This is a list of dictionaries which can decide whether files are
#   installed with the template or the copy module.
#
#   - dest: .gitignore                            mandatory
#     mode: 644                                   |default(0600)
#     force: true                                 |default(false)
#     src: files/project/.gitignore               |default(omit)
#     content: "foo"                              alternative to src
#     template: templates/project/.gitignore.j2   alternative to src or content: install dest with template module
#
#   template, src and content are mutualy exclusive for its meaning.
#     There is no technical enforcement for this. It depends on Ansible
#     what would happen if all keys are available for an item.
#
project_files:
  - dest: .gitignore
    src: files/project/.gitignore
    force: true
  - dest: ansible.cfg
    template: project/ansible.cfg.j2
  - dest: requirements.yml
    src: files/project/requirements.yml
  - dest: playbook.yml
    src: files/project/playbook.yml
  - dest: deployment.yml
    src: files/project/deployment.yml
  - dest: VERSION
    content: "0.0.1\n"
  - dest: README.md
    template: project/README.md.j2
  - dest: CHANGELOG.md
    src: files/project/CHANGELOG.md
  - dest: Vagrantfile
    template: project/Vagrantfile.j2
  - dest: playbook.yml
  - dest: files/.gitkeep
    force: true
    empty: true
  - dest: templates/.gitkeep
    force: true
    empty: true
  - dest: hosts
    empty: true
  - dest: host_vars/.gitkeep
    force: true
    empty: true
  - dest: group_vars/all/general.yml
    template: project/group_vars/all/general.yml.j2
  - dest: group_vars/prod/general.yml
    src: files/project/prod/general.yml
  - dest: group_vars/test/general.yml
    src: files/project/test/general.yml
  - dest: group_vars/stage/general.yml
    src: files/project/stage/general.yml
  - dest: group_vars/vagrant/secrets.yml
    content: "---\n# write all secrets here"
  - dest: group_vars/vagrant/general.yml
    template: project/group_vars/vagrant/general.yml.j2


# helper vars to ease template and play management
project_no_ssh_pipelining: False

project_name_nodash: "{{ project_name|regex_replace('[^a-zA-Z0-9]', '') }}"
