---
project_dirs:
  - dest: files
  - dest: roles
  - dest: group_vars
  - dest: group_vars/all
  - dest: group_vars/vagrant
  - dest: hosts_vars
  - dest: templates
  - dest: vars

project_files:
  - dest: .gitignore
    src: files/.gitignore
  - dest: ansible.cfg
    src: files/ansible.cfg.project
  - dest: requirements.yml
    content: "---\n"
  - dest: VERSION
    content: "0.0.1\n"
  - dest: README.md
    template: README.md.project.j2
  - dest: CHANGELOG.md
    src: files/CHANGELOG.md
  - dest: Vagrantfile
    template: Vagrantfile.project.j2
  - dest: playbook.yml
  - dest: files/.gitkeep
    empty: true
  - dest: roles/.gitkeep
    empty: true
  - dest: templates/.gitkeep
    empty: true
  - dest: hosts
    empty: true
  - dest: hosts_vars/.gitkeep
    empty: true
  - dest: group_vars/all/general.yml
    template: group_vars/all/general.yml
  - dest: group_vars/vagrant/secrets.yml
    content: "---\n# write all secrets here"
  - dest: group_vars/vagrant/general.yml
    template: group_vars/vagrant/general.yml
