---
project_dirs:
  - dest: files
  - dest: group_vars
  - dest: group_vars/all
  - dest: group_vars/dev
  - dest: group_vars/prod
  - dest: group_vars/test
  - dest: group_vars/vagrant
  - dest: host_vars
  - dest: templates
  - dest: vars

project_files:
  - dest: .gitignore
    src: files/project/.gitignore
    force: true
  - dest: ansible.cfg
    template: project/ansible.cfg.j2
  - dest: requirements.yml
    src: files/project/requirements.yml
  - dest: bootstrap.yml
    src: files/project/bootstrap.yml
  - dest: infrastructure.yml
    content: "---\n"
  - dest: deployment.yml
    content: "---\n"
  - dest: VERSION
    content: "0.0.1\n"
  - dest: README.md
    template: project/README.md.j2
  - dest: CHANGELOG.md
    src: files/project/CHANGELOG.md
  - dest: Vagrantfile
    template: project/Vagrantfile.j2
  - dest: playbook.yml
  - dest: files/.gitkeep
    force: true
    empty: true
  - dest: templates/.gitkeep
    force: true
    empty: true
  - dest: hosts
    empty: true
  - dest: host_vars/.gitkeep
    force: true
    empty: true
  - dest: group_vars/all/general.yml
    template: project/group_vars/all/general.yml.j2
  - dest: group_vars/dev/.gitkeep
    force: true
    empty: true
  - dest: group_vars/prod/.gitkeep
    force: true
    empty: true
  - dest: group_vars/test/.gitkeep
    force: true
    empty: true
  - dest: group_vars/vagrant/secrets.yml
    content: "---\n# write all secrets here"
  - dest: group_vars/vagrant/general.yml
    template: project/group_vars/vagrant/general.yml.j2

project_no_ssh_pipelining: False
